import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Sidebar from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <div className="flex min-h-screen flex-col">
          {/* Top Header */}
          <header>
            <div className="mx-auto max-w-7xl px-4 py-4">
              <Header />
            </div>
          </header>

          {/* Main Content with Sidebar */}
          <main className="flex flex-1">
            {/* Sidebar Left */}
            <Sidebar />

            {/* Page Content */}
            <div className="flex-1 px-4 py-6">{children}</div>
          </main>

          {/* Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
